### PR TITLE
Registry auth keys to accept more formats

### LINKED ISSUE #453: Should allow URL schema in auth configs, like dockerconfig does.
This results in auth error:
```YAML
registry:
  auths:
    "https://gcr.io":
      auth: "..."
```
...but this works:
```YAML
registry:
  auths:
    "gcr.io":
      auth: "..."
```

### PR DESCRIPTION
**Pull request by philwinder**
Added url parse with a bit of jiggery pokery to parse more formats.
Added test to ensure all formats are parsed properly.

Fixes #453

### CODE REVIEW

File: registry/remote_factory_test.go [hunk 1]
```diff
@@ -123,7 +123,59 @@ func TestRemoteFactory_CredentialsFromConfigHTTPSHosts(t *testing.T) {
...
+		{
+			host:        "https://gcr.io",
+			imagePrefix: "gcr.io",
+		},
+		{
+			host:        "https://gcr.io/v1",
+			imagePrefix: "gcr.io",
+		},
+		{
+			host:        "https://gcr.io/v1/",
```
Comment (paulbellamy) [inline registry/remote_factory_test.go]: maybe another scheme as well for completeness, e.g. `telnet://gcr.io/v1`

Comment (paulbellamy) [inline registry/remote_factory_test.go]: Should probably also test some malformed ones, and what happens...
`"https://"`
`""`
`"/usr/local"`
