### PR TITLE
Annotate resources outside of HelmRelease NS

### LINKED ISSUE #1293: helm-operator:  does not match namespace
In some charts (e.g. coreos/kube-prometheus) a few resource is created in the "kube-system" namespace, and not in the release namespace.
helm-operatot logs this error:

```
ts=2018-08-17T12:56:44.566927601Z caller=release.go:296 component=release output="secret \"alertmanager-monitoring\" annotated\n[...]servicemonitor \"monitoring-prometheus\" annotated\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\n" err="exit status 1"
```

Despite of this error, the release seems working fine.

### PR DESCRIPTION
**Pull request by hiddeco**
Fixes #1293

### CODE REVIEW

File: integrations/helm/release/release.go [hunk 1]
```diff
@@ -296,3 +298,49 @@ func mergeValues(dest, src chartutil.Values) chartutil.Values {
...
+	}
+	return objs
+}
+
+func namespacedResourceMap(objs []unstructured.Unstructured, defaultNamespace string) map[string][]string {
+	resources := make(map[string][]string)
+	for _, obj := range objs {
+		namespace := obj.GetNamespace()
+		if namespace == "" {
+			namespace = defaultNamespace
```
Comment (squaremo) [inline integrations/helm/release/release.go]: The name `defaultNamespace` misled me into thinking this code was fallible, since it had to be given a hard-wired default namespace. But it's OK in fact, because it is the release namespace that is passed, which is indeed the namespace given to anything that needs a namespace and hasn't got one. Would calling the argument `releaseNamespace` make this clearer do you think, or am I just obsessed with default namespaces after #1442?

File: integrations/helm/release/release.go [hunk 2]
```diff
@@ -296,3 +298,49 @@ func mergeValues(dest, src chartutil.Values) chartutil.Values {
...
+	var objs []unstructured.Unstructured
+	for _, manifest := range manifests {
+		json, err := yaml.YAMLToJSON([]byte(manifest))
+		if err != nil {
+			logger.Log("err", err)
+			continue
+		}
+
+		var u unstructured.Unstructured
+		if err := u.UnmarshalJSON(json); err != nil {
```
Comment (squaremo) [inline integrations/helm/release/release.go]: This made me pause for thought -- the usual formulation is

```
var u unstructured.Unstructured
if err := json.Unmarshal(bytes, &u); err != nil {
 ...
}
```

.. though this code will work fine, so far as I know (it's just eliding the dispatch which json.Unmarshal would do after checking `&u` implemented `json.Unmarshaler`)

File: integrations/helm/release/release.go (hunk 1 above)
Comment (hiddeco) [reply integrations/helm/release/release.go]: It misled me too now that I hadn't seen this code in a couple of days, which is a sign. Will adjust it.

File: integrations/helm/release/release.go (hunk 2 above)
Comment (hiddeco) [reply integrations/helm/release/release.go]: The reason I choose for `u.UnmarshalJSON` and not the common `json.Unmarshal` is that it makes use of `UnstructuredJSONScheme`, which to my knowledge does some sanity checks; it will for example fail if there is no `kind` key set.

This may however be over engineered and I am happy to change it to a simpler approach.

Comment (squaremo) [reply integrations/helm/release/release.go]: Additional checks are good :+1: `json.Unmarshal` will end up calling `UnmarshalJSON` for anything that implements it, so you will still get those.
