### PR TITLE
Make all Helm releases through the operator

### LINKED ISSUE #1820: Flux reports failure for helm chart and then success
While debugging for #1819, I deleted the helm release and then flux reported failure deploying the chart followed immediately by a success message:

```
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.837039819Z caller=operator.go:301 component=operator info="UPGRADING release"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.837086515Z caller=operator.go:305 component=operator info="Custom Resource driven release upgrade"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.843287719Z caller=operator.go:172 component=operator debug="PROCESSING item [\"production-namespace/production-app\"]"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.843328979Z caller=operator.go:229 component=operator debug="Starting to sync cache key production-namespace/production-app"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.8616102Z caller=release.go:139 component=release info="processing release production-app" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.959282774Z caller=release.go:186 component=release error="Chart release failed: production-app: &status.statusError{Code:2, Message:\"release production-app failed: Deployment in version \\\"v1beta2\\\" cannot be handled as a Deployment: v1beta2.Deployment.Spec: v1beta2.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity: readObjectStart: expect { or n, but found \\\", error found in #10 byte of ...|ffinity\\\":\\\"podAntiAff|..., bigger context ...|se\\\":\\\"production-app\\\"}},\\\"spec\\\":{\\\"affinity\\\":\\\"podAntiAffinity:\\\\n  preferredDuringSchedulingIgnor|...\", Details:[]*any.Any(nil)}"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:17.987413038Z caller=release.go:190 component=release info="Deleting failed release: [production-app]"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:18.119739783Z caller=operator.go:214 component=operator info="Successfully synced 'production-namespace/production-app'"
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: ts=2019-03-13T11:15:18.121657468Z caller=operator.go:169 component=operator debug="Processing next work queue job ..."
flux/flux-helm-operator-7fb864d794-2wrnk[flux-helm-operator]: I0313 11:15:18.121287       7 event.go:221] Event(v1.ObjectReference{Kind:"HelmRelease", Namespace:"production-namespace", Name:"production-app", UID:"5aea4958-44e1-11e9-a0f1-02dab9d7b196", APIVersion:"flux.weave.works/v1beta1", ResourceVersion:"1444304", FieldPath:""}): type: 'Normal' reason: 'ChartSynced' Chart managed by HelmRelease processed successfully
````

### LINKED ISSUE #1873: Helm Release Recreated After HelmRelease Is Garbage Collected
I'm having a strange issue with the new `--sync-garbage-collection` feature. Basically, when I remove a `HelmRelease` file from Git and commit it, Flux picks this up properly and deletes the corresponding `HelmRelease`, but it also appears to create a _new_ Helm release afterwards. This causes there to be orphaned Helm releases left without a corresponding `HelmRelease`, and thus, this needs to be cleaned up manually. Example log:
```
Mar 27 09:09:45 flux-helm-operator-6b4c7c767d-nvzcx.flux.derp flux-helm-operator: ts=2019-03-27T16:09:45.191264505Z caller=release.go:147 component=release info="processing release test (as dbbb37c2-50a8-11e9-8ff7-16b5dbb64816)" action=CREATE options="{DryRun:true ReuseName:false}" timeout=300s
Mar 27 09:11:22 flux-5f5c67fb69-jwv7s.flux.derp flux: ts=2019-03-27T16:11:22.154589668Z caller=sync.go:135 component=cluster info="cluster resource not in resources to be synced; deleting" resource=test:helmrelease/test
Mar 27 09:11:22 flux-5f5c67fb69-jwv7s.flux.derp flux: ts=2019-03-27T16:11:22.238287725Z caller=sync.go:483 component=cluster method=Sync cmd="kubectl delete -f -" took=83.580268ms err=null output="helmrelease.flux.weave.works \"test\" deleted"
Mar 27 09:11:23 flux-helm-operator-6b4c7c767d-nvzcx.flux.derp flux-helm-operator: ts=2019-03-27T16:11:23.63301596Z caller=release.go:116 component=release info="Deleting release test"
Mar 27 09:11:25 flux-helm-operator-6b4c7c767d-nvzcx.flux.derp flux-helm-operator: ts=2019-03-27T16:11:25.581917569Z caller=release.go:246 component=release info="Release deleted: [test]"
Mar 27 09:11:58 flux-helm-operator-6b4c7c767d-nvzcx.flux.derp flux-helm-operator: ts=2019-03-27T16:11:58.769620249Z caller=release.go:147 component=release info="processing release test (as test)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=300s
Mar 27 09:12:03 flux-helm-operator-6b4c7c767d-nvzcx.flux.derp flux-helm-operator: ts=2019-03-27T16:12:03.710489868Z caller=chartsync.go:361 component=chartsync warning="could not update the release revision" namespace=test resource=test err="helmreleases.flux.weave.works \"test\" not found"
```

### PR DESCRIPTION
**Pull request by hiddeco**
Fixes #1873, fixes #1820

This PR changes a couple of things in the Helm operator (details are commented in each commit), but in one sentence: it ensures all releases are made by the operator.

(If someone has a better one sentence recap of this PR; be my guest to change it)

### CODE REVIEW

**Comment by squaremo** [comment]
> * Trigger `HelmRelease` update on repository change to trigger an update through the operator, instead of calling the blocking `chs.reconcileReleaseDef(fhr)`. This can probably be done by adding, editing or removing an annotation on the `HelmRelease`, as those count as updates.

Per [your comment](https://github.com/weaveworks/flux/pull/1906/files#diff-55ed1cad6ef40f93631216da7abe34deR233), if we can do this via the controller/informer/thingdoer, that would be preferable I reckon .. IIRC though, it is tricky to get at the individual bits of a controller once you've constructed it, so it might require some contortions :-/

**Comment by hiddeco** [comment]
> Do not trigger update event on status changes

From my observations patching the subresource still triggers an update event @stefanprodan, from the brief discussion we had I thought this would not be the case. Is there something wrong with how I apply the patch or did we have a misunderstanding?

---

Besides that, PTAL @squaremo @2opremio, I think you will like it.

**Comment by squaremo** [comment]
> I think you will like it.

At `+192 −209` that seems a near certainty :-)

File: cmd/helm-operator/main.go [hunk 1]
```diff
@@ -169,27 +170,27 @@ func main() {
 	statusUpdater := status.New(ifClient, kubeClient, helmClient, *namespace)
 	go statusUpdater.Loop(shutdown, log.With(logger, "component", "annotator"))
 
-	// release instance is needed during the sync of Charts changes and during the sync of HelmRelease changes
+	nsOpt := ifinformers.WithNamespace(*namespace)
+	ifInformerFactory := ifinformers.NewSharedInformerFactoryWithOptions(ifClient, *chartsSyncInterval, nsOpt)
+	fhrInformer := ifInformerFactory.Flux().V1beta1().HelmReleases()
+	go ifInformerFactory.Start(shutdown)
+
+	queue := workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "ChartRelease")
```
Comment (2opremio) [inline cmd/helm-operator/main.go]: I would move this closer to where it's used

**Comment by 2opremio** [comment]
@hiddeco Have you reviewed the large comment at the beginning of `chartsync.go`? I would guess it requires updating.

**Comment by hiddeco** [comment]
@2opremio err, no, that caught my eye but got lost in my mind. Will rewrite it, good catch.

File: integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/fake/fake_helmrelease.go [hunk 2]
```diff
@@ -97,6 +97,18 @@ func (c *FakeHelmReleases) Update(helmRelease *v1beta1.HelmRelease) (result *v1b
 	return obj.(*v1beta1.HelmRelease), err
 }
 
+// UpdateStatus was generated because the type contains a Status member.
+// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
```
Comment (2opremio) [inline integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/fake/fake_helmrelease.go]: Wouldn't it be cleaner to place part of this comment at `v1beta1/types.go`?

e.g.
```
// Uncomment  to to avoid generating UpdateStatus()
// // +genclient:noStatus
```

File: integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go [hunk 3]
```diff
@@ -117,6 +118,22 @@ func (c *helmReleases) Update(helmRelease *v1beta1.HelmRelease) (result *v1beta1
 	return
 }
 
+// UpdateStatus was generated because the type contains a Status member.
+// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
```
Comment (2opremio) [inline integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go]: Same here

Comment (hiddeco) [reply integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go]: Both results of running `./bin/update-codegen.sh`.

Comment (stefanprodan) [reply integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go]: @2opremio everything inside the `client` package is generated by the Kubernetes CRD codegen.

Comment (2opremio) [reply integrations/client/clientset/versioned/typed/flux.weave.works/v1beta1/helmrelease.go]: thanks, I didn't know

**Comment by hiddeco** [comment]
@2opremio I addressed the comment block in `chartsync.go` by rewriting history (`5893fa0`).

**Comment by 2opremio** [comment]
It LGTM, but I am still no expert on the helm operator so I may be missing problems.

@stefanprodan mind taking a look?
