### PR TITLE
Harden and simplify yaml stream decoding/encoding

### LINKED ISSUE #1925: Weave cloud deploy page error with '---' at EOF
It appears that when flux syncs a yaml that has a '---' at the end of the file, the application works correctly, and the yaml is applied, but afterwards the Weave Cloud interface for deployments has the following error: 
```parsing YAML doc from "{pathToYaml}": yaml: did not find expected node content'```

When I remove the '---' at the end of the file, this error goes away.

The only effect this has is that it prevents me from doing manual deployments, and we could add validation for this, BUT this seems like a Weave specific problem that should be resolved, since it is valid kubernetes syntax.

### PR DESCRIPTION
**Pull request by 2opremio**
Flux choked on end-of-document markers (`...`).

To avoid complicating the existing multidoc parser (stolen from kubernetes) I abused `go-yaml`'s`Decoder` to obtain the raw documents from the stream by unmarshalling to an `interface{}` and marshalling again.

Also, I replaced our ad-hoc stream parsing and generation by a `go-yaml` `Decoder` and `Encoder`. 

I, however, left the encoding part of `fluxctl save` untouched since `yaml.Encoder` generates different output (no start-of-document prefix) and users may be relying on it.

During testing I made sure that changes I made in `fluxd`'s `Export()` are compatible with `fluxctl save` prior to this change.

Fixes #1925

### CODE REVIEW

File: cluster/kubernetes/resource/load.go [hunk 1]
```diff
@@ -159,45 +158,8 @@ func ParseMultidoc(multidoc []byte, source string) (map[string]KubeManifest, err
...
 	return objs, nil
 }
-
-// ---
-// Taken directly from https://github.com/kubernetes/apimachinery/blob/master/pkg/util/yaml/decoder.go.
-
-const yamlSeparator = "\n---"
-
-// splitYAMLDocument is a bufio.SplitFunc for splitting YAML streams into individual documents.
-func splitYAMLDocument(data []byte, atEOF bool) (advance int, token []byte, err error) {
```
Comment (hiddeco) [inline cluster/kubernetes/resource/load.go]: Although not related to this bugfix, another copy of this method can be found here: https://github.com/weaveworks/flux/blob/546ea7169eaede3da0b2193f09f263a35bec6474/cmd/fluxctl/save_cmd.go#L220

**Comment by 2opremio** [comment]
Uhm, I think I got something wrong. The test seems to pass without the code changes ...

File: cluster/kubernetes/resource/load.go (hunk 1 above)
Comment (2opremio) [reply cluster/kubernetes/resource/load.go]: yikes, that sucks

Comment (hiddeco) [reply cluster/kubernetes/resource/load.go]: Also totally not related to this PR, we probably want to include our GC labels and annotations here: https://github.com/weaveworks/flux/blob/546ea7169eaede3da0b2193f09f263a35bec6474/cmd/fluxctl/save_cmd.go#L102

Comment (2opremio) [reply cluster/kubernetes/resource/load.go]: I will fix the first part. I am not sure about the second, can you create a separate issue for it?

**Comment by squaremo** [comment]
Q: Does this mean comments are no longer preserved when files are updated by flux?

**Comment by squaremo** [comment]
A: no, because the kubeyaml-using code still just reads a whole file in, and writes a whole file out.

**Comment by 2opremio** [comment]
Yep, exactly, sorry I didn't get to answer the question in time.
