### PR TITLE
Invalidate discovery cache periodically

### LINKED ISSUE #1855: Fluxd can get stuck if started "too early" after a GKE cluster creation
I am testing the bootstrap of a cluster using flux on GKE , the whole configuration is managed with terraform.

1. terraform create gke cluster 
1. as soon as the creation of gke returns success flux is deployed 

in this case fluxd seems to fail to fetch some information from the apiserver and get stuck in a `collating resources in cluster for sync: not found` loop even though after a while , if it retried to fetch the apiserver info , it would succed

the error i can see is `ERROR: logging before flag.Parse: E0322 09:47:31.690724       6 memcache.go:147] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

```
ts=2019-03-22T09:47:23.281235971Z caller=main.go:165 version=1.11.0
ts=2019-03-22T09:47:23.317696094Z caller=main.go:295 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-03-22T09:47:23.317758233Z caller=main.go:296 component=cluster identity.pub="XXXX"
ts=2019-03-22T09:47:23.317785061Z caller=main.go:297 component=cluster host=https://10.0.88.1:443 version=kubernetes-v1.12.5-gke.10
ts=2019-03-22T09:47:23.317855927Z caller=main.go:309 component=cluster kubectl=/usr/local/bin/kubectl
ts=2019-03-22T09:47:23.319794947Z caller=main.go:319 component=cluster ping=true
ts=2019-03-22T09:47:23.375286258Z caller=aws.go:69 component=aws warn="no AWS region configured, or detected as cluster region" err="EC2MetadataError: failed to make EC2Metadata request\ncaused by: This metadata API is not allowed by the metadata proxy.\n"
ts=2019-03-22T09:47:23.375356788Z caller=main.go:344 warning="AWS authorization not used; pre-flight check failed"
ts=2019-03-22T09:47:23.381741151Z caller=main.go:449 url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git user="Weave Flux" email=support@weave.works signing-key= sync-tag=flux-sync-dev notes-ref=flux-sync-dev set-author=false
ts=2019-03-22T09:47:23.381838588Z caller=main.go:506 upstream="no upstream URL given"
ts=2019-03-22T09:47:23.383853937Z caller=main.go:535 metrics-addr=:3031
ts=2019-03-22T09:47:23.385475596Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-22T09:47:23.385516124Z caller=images.go:27 component=sync-loop msg="no automated services"
ts=2019-03-22T09:47:23.385837708Z caller=loop.go:90 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-03-22T09:47:23.387328006Z caller=main.go:527 addr=:3030
ts=2019-03-22T09:47:24.035019823Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.11.0
ts=2019-03-22T09:47:31.577869464Z caller=loop.go:103 component=sync-loop event=refreshed url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git branch=dev HEAD=4446db6c8225fd18b566219c2a41ce9a23a9d088
ERROR: logging before flag.Parse: E0322 09:47:31.690724       6 memcache.go:147] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
ts=2019-03-22T09:47:31.701396542Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:47:31.710863513Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:48:33.199756991Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:48:33.208266708Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:48:33.213800046Z caller=loop.go:103 component=sync-loop event=refreshed url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git branch=dev HEAD=4446db6c8225fd18b566219c2a41ce9a23a9d088
ts=2019-03-22T09:49:34.810247471Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:49:34.815635198Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-03-22T09:49:34.819879233Z caller=loop.go:103 component=sync-loop event=refreshed url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git branch=dev HEAD=4446db6c8225fd18b566219c2a41ce9a23a9d088
```

Deleting the pod let the new instance of flux complete its startup process properly

```
ts=2019-03-22T09:49:53.04497357Z caller=main.go:165 version=1.11.0
ts=2019-03-22T09:49:53.085897609Z caller=main.go:295 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-03-22T09:49:53.085976658Z caller=main.go:296 component=cluster identity.pub="XXXX
ts=2019-03-22T09:49:53.086178422Z caller=main.go:297 component=cluster host=https://10.0.88.1:443 version=kubernetes-v1.12.5-gke.10
ts=2019-03-22T09:49:53.086253208Z caller=main.go:309 component=cluster kubectl=/usr/local/bin/kubectl
ts=2019-03-22T09:49:53.087752566Z caller=main.go:319 component=cluster ping=true
ts=2019-03-22T09:49:53.090451181Z caller=aws.go:69 component=aws warn="no AWS region configured, or detected as cluster region" err="EC2MetadataError: failed to make EC2Metadata request\ncaused by: This metadata API is not allowed by the metadata proxy.\n"
ts=2019-03-22T09:49:53.090593122Z caller=main.go:344 warning="AWS authorization not used; pre-flight check failed"
ts=2019-03-22T09:49:53.096061273Z caller=main.go:449 url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git user="Weave Flux" email=support@weave.works signing-key= sync-tag=flux-sync-dev notes-ref=flux-sync-dev set-author=false
ts=2019-03-22T09:49:53.096125961Z caller=main.go:506 upstream="no upstream URL given"
ts=2019-03-22T09:49:53.096645904Z caller=main.go:535 metrics-addr=:3031
ts=2019-03-22T09:49:53.097625224Z caller=loop.go:90 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-03-22T09:49:53.097683867Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-03-22T09:49:53.098122543Z caller=images.go:27 component=sync-loop msg="no automated services"
ts=2019-03-22T09:49:53.100502392Z caller=main.go:527 addr=:3030
ts=2019-03-22T09:49:53.829431175Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.11.0
ts=2019-03-22T09:50:00.97629931Z caller=loop.go:103 component=sync-loop event=refreshed url=git@gitlab.com:mintel/satoshi/experimental/gitops-rendered-manifests.git branch=dev HEAD=4446db6c8225fd18b566219c2a41ce9a23a9d088
ts=2019-03-22T09:50:01.832938149Z caller=sync.go:417 component=cluster method=Sync cmd=apply args= count=9
ts=2019-03-22T09:50:02.745412087Z caller=sync.go:483 component=cluster method=Sync cmd="kubectl apply -f -" took=912.159534ms err=null output="namespace/cert-manager created\nnamespace/ingress created\nnamespace/vault created\ncustomresourcedefinition.apiextensions.k8s.io/certificates.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/challenges.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/clusterissuers.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/issuers.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/orders.certmanager.k8s.io created\ncustomresourcedefinition.apiextensions.k8s.io/vaults.vault.banzaicloud.com created"
```

Adding a sleep of 1 minute between the GKE cluster creation and the flux deployment creation `fixed` the problem. 

This feel more like a workaround rather than a fix though and makes me wonder if other apiserver errors might get flux stuck as well

### PR DESCRIPTION
**Pull request by 2opremio**
The cluster resource definitions may not be stable throughout the life of the cluster.

We were already invalidating the cache every time a CRD object was altered and replaying the CRD changes every 5 minutes.

However, that's not enough because CRD-unrelated changes seem to happen when the cluster bootstraps.

Fixes #1855

### CODE REVIEW

File: cluster/kubernetes/cached_disco.go [hunk 1]
```diff
@@ -96,7 +96,32 @@ func makeCachedDiscovery(d discovery.DiscoveryInterface, c crd.Interface, shutdo
...
 	return cachedDisco, store, controller
 }
+
+func (d *cachedDiscovery) invalidatePeriodically(shutdown <-chan struct{}) {
+	// Make the first period shorter since we may be bootstrapping a
+	// newly-created cluster and the resource definitions may not be
+	// complete/stable yet.
+	initialPeriodDuration := 1 * time.Minute
+	subsequentPeriodsDuration := 5 * initialPeriodDuration
+	isInitialPeriod := true
```
Comment (squaremo) [inline cluster/kubernetes/cached_disco.go]: It's a minor stylistic thing, but I reckon this could be simpler if you use a timer:

```
delay := 1 * time.Minute
￼subsequentDelay := 5 * time.Minute
timer := time.NewTimer(delay)
￼for {
￼ 	select {
￼ 	case <-timer.C:
￼		timer.Reset(subsequentDelay)
￼ 		d.Invalidate()
￼ 	case <-shutdown:
￼ 		return
￼ 	}
￼}
```

Comment (2opremio) [reply cluster/kubernetes/cached_disco.go]: Thanks, that's much cleaner
