### PR TITLE
Make it possible to overwrite image TS with label

### LINKED ISSUE #891: Image timestamps are incorrect
I'm not sure if this is a Docker registry issue or a Flux issue, but the "created" timestamp seems to be based off of the image layers. This means that if a newer build ends up containing the same content as an older build, it will appear to be an older image and Flux will not upgrade.

### PR DESCRIPTION
**Pull request by hiddeco**
This adds support for overwriting the image created at timestamp with labels which are set during build. Supported labels (for now) are the [Open Container Image (OCI) spec](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) and the [(legacy) Label Schema (LS) spec](http://label-schema.org/rc1/#build-time-labels).

We prioritize OCI over LS, with a fallback to the CreatedAt from the registry.

Fixes #891, addresses #1799, #1797, #746

### CODE REVIEW

**Comment by hiddeco** [comment]
As this PR changes behaviour (by prioritizing labels over the `CreatedAt` date from the registry) and is more a feature than a bugfix, I marked this as a `v1.13.0` milestone.

File: image/image.go [hunk 1]
```diff
@@ -223,6 +223,52 @@ func (i Ref) WithNewTag(t string) Ref {
...
+		c = l.Created.UTC().Format(time.RFC3339Nano)
+	}
+	encode := struct {
+		BuildDate string `json:"org.label-schema.build-date,omitempty"`
+		Created   string `json:"org.opencontainers.image.created,omitempty"`
+	}{BuildDate: bd, Created: c}
+	return json.Marshal(encode)
+}
+
+// UnmarshalJSON populates a Labels from JSON (as bytes). It's the
```
Comment (2opremio) [inline image/image.go]:
```suggestion
// UnmarshalJSON populates Labels from JSON (as bytes). It's the
```

File: image/image.go [hunk 2]
```diff
@@ -281,6 +329,19 @@ func (im *Info) UnmarshalJSON(b []byte) error {
 	return err
 }
 
+// CreatedTS returns the created at timestamp, prioritizing timestamps
+// from labels (set during build) over the created at from the Docker
+// registry.
```
Comment (2opremio) [inline image/image.go]: I think it would be good to explain why we are choosing that priority

File: image/image.go [hunk 3]
```diff
@@ -223,6 +223,52 @@ func (i Ref) WithNewTag(t string) Ref {
 	return img
 }
 
+// Labels has all the image labels we are interested in for an image
+// ref, the JSON struct tag keys should be equal to the label.
+type Labels struct {
```
Comment (2opremio) [inline image/image.go]: No strong opinion, but wouldn't it be more flexible to make this a map? (in case we end up adding more labels in the future).

I guess we can always make it a map in the future without breaking the JSON representation, right?

Comment (hiddeco) [reply image/image.go]: > I guess we can always make it a map in the future without breaking the JSON representation, right?

This is just a JSON object with key/values, so yeap, no worries.

Comment (2opremio) [reply image/image.go]: Makes sense

**Comment by 2opremio** [comment]
LGTM
