### PR TITLE
Use the exact credentials collected for the image domain

### LINKED ISSUE #896: Unable to fetch image tags for Dockerhub private repo
As of flux 1.2.0, the cache warmer is failing to fetch image tags from dockerhub private repos.

Example log output:
```
ts=2018-01-11T23:30:04.828130984Z caller=warming.go:154 component=warmer err="requesting tags: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```

The logs should also make it clear which image we're failing to fetch tags for.

### PR DESCRIPTION
**Pull request by squaremo**
1. add an argument for enabling request tracing in the registry client
2. put a bit of extra logging in to report the nature of credentials being used in the registry client
3. ask for credentials using the image's name, rather than the auth domain, since those can differ (e.g., index.docker.io vs auth.docker.io).

Fixes #896.

### CODE REVIEW

File: registry/credentials.go [hunk 1]
```diff
@@ -4,14 +4,23 @@ import (
...
 
 // Registry Credentials
 type creds struct {
-	username, password string
+	username, password   string
+	registry, provenance string
+}
+
+func (c creds) String() string {
+	if c.username == "" && c.password == "" && c.registry == "" && c.provenance == "" {
```
Comment (sambooo) [inline registry/credentials.go]: This can be `if c == creds{}` and that's better because

Comment (squaremo) [reply registry/credentials.go]: Oh yeah!

**Comment by squaremo** [comment]
Thanks @tamarakaufler and @sambooo
