### PR TITLE
Ignore discovery errors for metrics resources

### LINKED ISSUE #1991: Sync fails due to metrics.k8s.io discovery error
Hello All,

While following the steps, i am getting the below error on the flux and not able to run any workload using the flux:

```ts=2019-04-29T04:06:36.714545618Z caller=images.go:18 component=sync-loop msg="polling images"
ts=2019-04-29T04:06:36.714622818Z caller=images.go:28 component=sync-loop msg="no automated workloads"
ts=2019-04-29T04:06:43.293711087Z caller=loop.go:103 component=sync-loop event=refreshed url=git@github.com:xxxxxxx/xxxxxx branch=master HEAD=c38943df8dde8b4ffda98a050e6f643ec712ccc3
ts=2019-04-29T04:06:43.528694435Z caller=main.go:199 type="internal kubernetes error" err="couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
ts=2019-04-29T04:06:43.528789635Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-04-29T04:06:43.531861734Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-04-29T04:11:36.714944593Z caller=images.go:18 component=sync-loop msg="polling images"
ts=2019-04-29T04:11:36.818370548Z caller=main.go:199 type="internal kubernetes error" err="couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
ts=2019-04-29T04:11:44.168625836Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-04-29T04:11:44.171171938Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-04-29T04:11:44.172498339Z caller=loop.go:103 component=sync-loop event=refreshed url=git@github.com:xxxxxx/xxxxxxxx branch=master HEAD=c38943df8dde8b4ffda98a050e6f643ec712ccc3
ts=2019-04-29T04:16:36.825719462Z caller=images.go:18 component=sync-loop msg="polling images"
ts=2019-04-29T04:16:36.939251772Z caller=main.go:199 type="internal kubernetes error" err="couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
ts=2019-04-29T04:16:45.041430658Z caller=loop.go:210 component=sync-loop err="collating resources in cluster for sync: not found"
ts=2019-04-29T04:16:45.04355066Z caller=loop.go:90 component=sync-loop err="collating resources in cluster for sync: not found"```

Any help will be appreciated.

### PR DESCRIPTION
**Pull request by 2opremio**
The Metrics API tends to be misconfigured, causing discovery errors which ultimately makes syncs fail.

This change makes Flux ignore those errors.

Fixes #1991

### CODE REVIEW

File: cluster/kubernetes/sync.go [hunk 1]
```diff
@@ -206,6 +206,11 @@ func (c *Cluster) getAllowedResourcesBySelector(selector string) (map[string]*ku
 			return nil, err
 		}
 		for gv, e := range discErr.Groups {
+			if strings.HasSuffix(gv.Group, "metrics.k8s.io") {
+				// The Metrics API tends to be misconfigured, causing errors.
+				// We just ignore them, since it doesn't make sense to sync metrics anyways.
```
Comment (2opremio) [inline cluster/kubernetes/sync.go]: @stefanprodan can you confirm whether this is true? I am not that familiar with the metrics API.

**Comment by 2opremio** [comment]
Since this is the third time we have problems with the discovery API (before #1991 we had #1951 and before that #1855) I think this may happen again with other resources in the future. I am tempted to ignore the partial list of resources affected by `discovery.ErrGroupDiscoveryFailed` like ArgoCD does https://github.com/argoproj/argo-cd/pull/526

@hiddeco @squaremo thoughts?

File: cluster/kubernetes/sync.go (hunk 1 above)
Comment (stefanprodan) [reply cluster/kubernetes/sync.go]: GKE comes with the metrics server and it registers the `metrics.k8s.io` at bootstrap. For EKS and AKS where you would install the metrics server with Helm, I don't think it will be an issue and for GKE ignoring it will not cause any problems as far as I can tell.

**Comment by hiddeco** [comment]
@2opremio your suggestion makes more sense to me as I have the feeling we will otherwise forever be patching specific resources.

**Comment by 2opremio** [comment]
After further thinking, all the errors we've had were in one way or another related to metrics. So I think it's worth giving it a try (I am not too happy about ignoring errors, unless we are sure about the impact). If it fails again with a different resource, I will be happy to ignore `discovery.ErrGroupDiscoveryFailed`.

**Comment by sercanacar** [comment]
Temporary fix for this? I've tried removing helmrelease for metrics-server...no luck

**Comment by 2opremio** [comment]
@sercanacar I don't know what causes the error, sorry. I would assume it's a problem with the metrics server so I would suggest to double-check it's uninstalled.

@stefanprodan any suggestions?

**Comment by 2opremio** [comment]
@sercanacar you can upgrade to 1.12.2, which contains the fix
